[project]
name = "python-container-demo"
version = "0.1.0"
description = "Show how to build container images for a python project managed by uv"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["flask>=3.1.0", "waitress>=3.0.2"]
